site_name: 2020_5DI_Team3
nav:
    - 'Vision Statement': 'Vision_Statement.md'
    - 'Software Requirement Specification': 'Software_Requirement_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Release Plan': 'Release_Plan.md'
    - 'Iteration Plan': 'Iteration_Plan.md'
    - 'Memo Of Understanding': 'Memo_Of_Understanding.md'
    - 'Project Success Criteria': 'Project_Success_Criteria.md'
    - 'Architecture, Design and Coding Standards': 'Architecture,_Design_and_Coding_Standards.md'
    - 'Test Plan': 'Test_Plan.md'
    - 'Business Model': 'business_model.pdf'
    - 'Project Model': 'Project_Mode.pdf'
    
theme:
    name: readthedocs


