site_name: 2020_5DI_Team3
nav:
    - 'Vision Statement': 'Vision_Statement.md'
    - 'Software Requirement Specification': 'Software_Requirement_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Release Plan': 'Release_Plan.md'
    - 'Iteration Plan': 'Iteration_Plan.md'
    - 'Memo Of Understanding': 'Memo_Of_Understanding.md'
    - 'Project Success Criteria': 'Project_Success_Criteria.md'
    - 'Architecture, Design and Coding Standards': 'Architecture_Design_and_Coding_Standards.md'
    - 'Test Plan': 'Test_Plan.md'
    - 'Test Case Specification': 'Test_Case_Specification.md'
    - 'System Documentation': 'System_Documentation.md'
    - 'User Guide': 'User_Guide.md'
    - 'Vision Statement(PDF)': 'Vision Statement.pdf'
    - 'Software Requirement Specification(PDF)': 'Software Requirement Specification.pdf'
    - 'Software Project Management Plan(PDF)': 'Software Project Management Plan.pdf'
    - 'Release Plan(PDF)': 'Release Plan.pdf'
    - 'Iteration Plan(PDF)': 'Iteration Plan.pdf'
    - 'Memo Of Understanding(PDF)': 'Memo_of_understanding.pdf'
    - 'Project Success Criteria(PDF)': 'Success Criteria for SF - Agricolture Projects.pdf'
    - 'Architecture, Design and Coding Standards(PDF)': 'Architecture and design.pdf'
    - 'Test Plan(PDF)': 'Test Plan.pdf'
    - 'System Documentation(PDF)': 'System_Documentation.pdf'
    - 'User Guide(PDF)': 'User_Guide.pdf'
    - 'Test Case Specification(PDF)': 'Test_Case_Specification.pdf'
    - 'Business Model': 'business_model.pdf'
    - 'Project Model': 'Project_Mode.pdf'
    
theme:
    name: readthedocs


